# -*- coding: utf-8 -*-
"""02/03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11NV72P7WVafGK-Vm8UC2C0LVJltj4ajK
"""

nota1= float(input ("digite a primeira nota: "))
nota2= float(input ("digite a segunda nota: "))
notaSemestre= ((nota1 * 4) + (nota2 * 6)) / 10
print ("sua nota semestral é ",notaSemestre)