# -*- coding: utf-8 -*-
"""17/03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Q3t8p8I0jljLXt8RScrctoIMcQfsuVN
"""

numero= float(input ("digite um número inteiro: "))

dobro= numero * 2

print ("o dobro de",numero,"é",dobro)