# -*- coding: utf-8 -*-
"""1aula

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZU8ovKVXsPt_NMN5cm4n_xqwJ3ckrbT
"""

n1=4
n2=2

soma=n1+n2
sub=n1-n2
div=n1//n2
multi=n1*n2
exp=n1**n2
conta2= n1 + n2 * n1**n2 - n1//n2

import math
num=float(input("escreva um número:\n"))
raiz=math.sqrt(num)

print("a soma dos números é:", soma)
print("a subtração dos números é:", sub)
print("a divisão dos números é:", div)
print("a multiplicação dos números é:", multi)
print("a exponenciação dos números é:", exp)
print("a expressão dos números é:", conta2)
print("a raiz quadrada do número é:", raiz)

"""# Nova seção"""