# -*- coding: utf-8 -*-
"""bhaskara

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15wpDH7VfOBGWBhYUbcFWU-ZsJiEIMNjd
"""

A= float(input ("digite o valor de A: "))
B= float(input ("digite o valor de B: "))
C= float(input ("digite o valor de C: "))
print ("EQUAÇÃO: ",A,"X² + ",B,"X + ",C)
delta= B**2 -4 * A * C
if (delta > 0):
  print ("DELTA: ",delta)
  print ("a equação possui duas raízes diferentes")
  x1= (-B + delta**(1/2)) / (2 * A)
  x2= (-B - delta**(1/2)) / (2 * A)
  print ("X1= ",x1)
  print ("X2= ",x2)
if (delta == 0):
     print ("DELTA: ",delta)
     print ("a equação possui apenas uma raiz")
     x1= -B / (2 * A)
     print ("X1= ",x1)
if (delta < 0):
      print ("DELTA: ",delta)
      print ("não existem raízes")

