# -*- coding: utf-8 -*-
"""cadastrar-clientes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeAmozQiQQXpm30C3zCn5z_yQsA0wRC6
"""

clientes = []

def cadastrar_cliente():
  nome = input("\nNome: ")
  sobrenome = input("Sobrenome: ")
  idade = int(input("Idade: "))
  email = input("Email: ")

  while True:
    try:
      telefone = int(input("Telefone: "))
      break
    except ValueError:
      print ("\nPor favor, digite novamente apenas números, sem espaços\n")

  endereco = input("Endereço: ")

  cliente = {
      "Nome": nome,
      "Sobrenome": sobrenome,
      "Idade": idade,
      "Email": email,
      "Telefone": telefone,
      "Endereço": endereco
  }

  clientes.append(cliente)
  print ("\nCliente adicionado com sucesso!\n")

def consultar_cliente():

  if not clientes:
    resposta = input("Nenhum cliente cadastrado, deseja adicionar?: ")
    if resposta == "sim" or "Sim" or "s" or "S":
      cadastrar_cliente()
    elif resposta == "não" or "n" or "N" or "Não" :
      print("Ok!\n")
    else:
      print("Resposta inválida\n")

  else:
    for cliente in clientes:
      print(f"\nNome: {cliente['Nome']} {cliente['Sobrenome']}")
      print(f"Idade: {cliente['Idade']} anos | Email: {cliente['Email']}")
      print(f"Telefone: {cliente['Telefone']} | Endereço: {cliente['Endereço']}\n\n")

def exportar_arquivo():
  with open('clientes.txt', 'w') as arquivo:
    for cliente in clientes:
      arquivo.write("%s\n" % cliente)
    arquivo_txt = open('clientes.txt', 'r')
    print(arquivo_txt.read())

    print("Arquivo exportado com sucesso!\n")

def remover_cliente():
  while True:
    cliente_removido = input("\nDigite o nome do cliente para ser removido: ")
    cliente_encontrado = None

    for cliente in clientes:
        if cliente['Nome'] == cliente_removido:
            cliente_encontrado = cliente
            break

    if cliente_encontrado is not None:
        clientes.remove(cliente_encontrado)
        print("\nO cliente foi removido com sucesso!\n")
        break
    else:
        print("\nO(a) cliente ",cliente_encontrado," não está na lista.")

print ("PROGRAMA DE CADASTRO DE CLIENTES\n")

while True:
  try:
    print ("MENU\n")
    print ("1. Cadastrar cliente")
    print ("2. Consultar clientes")
    print ("3. Exportar arquivo")
    print ("4. Alterar cadastro")
    print ("5. Encerrar")

    opcao = int(input("\nDigite a opção desejada: "))

    if opcao == 1:
      cadastrar_cliente()
    elif opcao == 2:
      consultar_cliente()
    elif opcao == 3:
      exportar_arquivo()
    elif opcao == 4:
      remover_cliente()
    elif opcao == 5:
      print("Encerrando programa...")
      break
    else:
      print("Opção inválida.\n")
  except ValueError:
    print("Somente os números de acordo com o menu.\n")