# -*- coding: utf-8 -*-
"""calculo de area

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7ZKs_qxvy8SlIaA0mXJqDhN_C6bKaCp
"""

print("digite a base menor em metros")
base1= float(input ())
print("digite a base maior em metros")
base2= float(input ())
print ("digite a altura em metros")
altura= float(input())
area=(base1+base2) * altura /2
print("a área do trapézio é de ", area, "m²")



