# -*- coding: utf-8 -*-
"""calculo salario

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHBbWwfyOS856iaSLM-vmtFaFNsWEHEt
"""

salBruto= float(input ("digite o seu salário: "))
dep= float(input ("digite o número de dependentes: "))

if (salBruto <= 1100):
  inss= salBruto * 7.5 / 100
elif ((salBruto >= 1100.01) and (salBruto <= 2203.48 )):
  inss= salBruto * 9 / 100
elif ((salBruto >= 2203.49) and (salBruto <= 3305.22)):
  inss= salBruto * 12 / 100
else:
  inss= salBruto * 14 / 100

form_ir= salBruto - inss - (189.59 * dep)

if (form_ir <= 1903.98):
  ir= 0
elif ((form_ir >= 1903.99) and (form_ir <= 2826.85)):
  ir= 7.5 * salBruto / 100
elif ((form_ir >= 2826.86) and (form_ir <= 3751.05)):
  ir= salBruto * 15 / 100
elif ((form_ir >= 3751.06) and (form_ir <= 4664.68)):
  ir= salBruto * 22.5 / 100
else:
  ir= salBruto * 27.5 / 100

salLiq= salBruto - inss - ir - (189.59 * dep)
print ("seu salário líquido é de R$",salLiq)