# -*- coding: utf-8 -*-
"""hhfhj use

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KAwOUp845gneIyFYUZNzzD5PWQXwn38m
"""

cigDia= int(input("quantos cigarros você fuma por dia?: "))
anos= int(input("quantos anos você já fumou?: "))
tempoVidaMin= cigDia*10*365*anos
tempoVidaDia= tempoVidaMin / 1440
print ("voce perderá aprox. ",tempoVidaDia," dias de vida")

