# -*- coding: utf-8 -*-
"""listas 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOKTP9lfxCs2jGl5Febp2wMUJl4xhjo6
"""

convidados = ["ravi", "caio", "manu", "duda", "rossi"]

while True:
  print("menu: \n")
  print("a) inserir nome de convidado")
  print("b) remover nome de convidado")
  print("c) exibir número de convidados")
  print("d) exibir lista de convidados em ordem alfabética")
  print("e) sair")

  opcao = input("digite a opção desejada: ")

  if opcao == "a":
    nome = input("digite o nome do convidado: ")
    convidados.append(nome)
    print(f"convidado adicionado com sucesso!\n")
  elif opcao == "b":
    nome = input("digite o nome do convidado a ser removido: ")
    if nome in convidados:
      convidados.remove(nome)
      print(f"convidado {nome} removido com sucesso!\n")
    else:
      print("o nome digitado não está na lista de convidados\n")
  elif opcao == "c":
    total_c= len(convidados)
    print(f"total: {total_c} convidados\n")
  elif opcao == "d":
    ord_afbt= sorted(convidados)
    print(f"lista de convidados em ordem alfabética: ")
    for convidado in ord_afbt:
      print(convidado)
  elif opcao == "e":
    print("encerrando o programa...\n")
    break
  else:
    print("digite uma opção válida\n")

notas = []

x=1
while x <= 5:
  nota= input(f"digite a {x}° nota: ")
  notas.append(nota)
  x+=1

print(f"lista de notas {notas}")

notas= ["8", "5", "8","9.9"]

print ("REMOVER NOTA MAIS BAIXA\n")
nota = min(notas)
notas.remove(nota)
print(f"lista atualizada: {notas}")

nomes = ["jose da silva","arthur morgan","peter parker","josé bezerra"]
while True:

    consulta = input("digite aqui um nome: ")
    if consulta in nomes:
      print(f"o nome {consulta} foi encontrado")
    else:
      print("seu nome nao foi encontrado")

    resp = input("deseja exportar a lista para um arquivo: ")
    if resp == "sim":
     with open('nome.txt', 'w') as arquivo:
       for consulta in nomes:
	       arquivo.write(nome + "/n")

nomes = ["jose da silva","arthur morgan","peter parker","josé bezerra"]
while True:
  nome= input("digite um nome para consulta: ")
  if nome in nomes:
    print (f"o nome {nome} foi encontrado")
  else:
    print (f"o nome {nome} nao foi encontrado")
  export= input("deseja exportar a lista para um arquivo?: ")
  if export == "sim":
    with open('arquivo_ravi.txt', 'w') as ludmilla:
      for nome in nomes:
        ludmilla.write("%s\n" % nome)
    arquivo= open('arquivo_ravi.txt', 'r')
    print (arquivo.read())

  else:
    print ("encerrando programa")
    break

lista= []
while True:
  print ("GERENCIAMENTO DE TAREFAS ESCOLARES\n")
  print ("MENU")
  print ("---------")
  print ("a) adicionar tarefas;")
  print ("b) remover tarefas;")
  print ("c) exibir lista de tarefas;")
  print ("d) sair;")

  opcao = input("\ndigite a opção desejada: ")

  if opcao == "a":
    tarefa = input("digite a tarefa que você deseja adicionar: ")
    lista.append(tarefa)
    print (f"a tarefa '{tarefa}' foi adicionada com sucesso!\n")
  elif opcao == "b":
    tarefa = input("digite qual tarefa você deseja remover: ")
    if tarefa in lista:
      lista.remove(tarefa)
      print (f"a tarefa '{tarefa}' foi removida com sucesso!\n")
    else:
      resposta= input("a tarefa digitada não está na lista, deseja remover outra?: ")
      if resposta == "sim":
         tarefa = input("digite qual tarefa você deseja remover: ")
         lista.remove(tarefa)
         print (f"a tarefa '{tarefa}' foi removida com sucesso!\n")
      elif resposta == "não":
        print ("saindo...\n")
      else:
        print ("opção inválida\n")
  elif opcao == "c":
    print (f"lista atualizada: {lista}\n")
  elif opcao == "d":
    print ("encerrando programa...\n")
    break
  else:
    print ("opção inválida\n")
  with open('tarefas_do_henderson.txt', 'w') as ravi:
    for tarefas in lista:
      ravi.write("%s\n" % tarefas)
    arquivo = open('tarefas_do_henderson.txt', 'r')
    print (arquivo.read())