# -*- coding: utf-8 -*-
"""lista de ex

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ebzA53k__c8wzGgmoUYKWi7BVBOlV667
"""

nome= str(input ("digite seu nome: "))
n1= float(input ("digite um número inteiro: "))
idade= float(input ("digite sua idade em 2020: "))

diferenca= idade - n1

print (nome,", a diferença da sua idade em 2020 e do seu número escolhido é de ",diferenca)

idade= float(input ("digite sua idade: "))

if (idade >=16):
  print ("você já pode votar")
else:
  print ("você ainda não pode votar")

n1= float(input ("digite um número: "))
n2= float(input ("digite mais um número: "))

if (n1 > n2):
  print ("o maior número é ",n1)
else:
  print ("o maior número é ",n2)

nota= float(input ("digite sua nota: "))

if (nota >= 7):
  print ("APROVADO")
else:
  print ("REPROVADO")

numero= float(input ("digite um número: "))

if (numero > 0):
  print ("o número ",numero," é positivo")
elif (numero == 0):
  print ("o número ",numero," é igual 0")
else:
  print ("o número ",numero," é negativo")

nota1= float(input ("digite a 1° nota: "))
nota2= float(input ("digite a 2° nota: "))
nota3= float(input ("digite a 3° nota: "))

media= (nota1 + nota2 + nota3) /3

if (media >= 7):
  print ("MÉDIA: ",media,"\n")
  print ("APROVADO")
else:
  print ("MÉDIA: ",media,"\n")
  print ("REPROVADO")

numero= float(input ("digite um número inteiro: "))

resto1= numero % 3
resto2= numero % 7

if (resto1 == 0):
  if (resto2 == 0):
    print ("o número ",numero," é divísivel por 3 e por 7")
if (resto1 == 0):
  if (resto2 != 0):
    print ("o número ",numero," não é divísivel pelos 2 ao mesmo tempo")
if (resto1 != 0):
  if (resto2 == 0):
    print ("o número ",numero," não é divísivel pelos 2 ao mesmo tempo")
if (resto1 != 0):
  if (resto2 != 0):
    print ("o número ",numero," não é divísivel por nenhum dos dois")

idade= int(input ("digite sua idade: "))

if (idade <= 12):
  print ("você é uma criança")
elif (idade <= 18):
    print ("você é um adolescente")
else:
 print ("adulto")

n1= float(input ("digite um número: "))
n2= float(input ("digite um número: "))

soma= n1 + n2
resto= soma % 2

if (resto == 0):
  print ("SOMA: ",soma,"\n")
  print ("a soma dos dois números é par")
else:
  print ("SOMA: ",soma,"\n")
  print ("a soma dos dois números é ímpar")

peso= float(input ("digite seu peso em KG: "))
altura= float(input ("digite sua altura em metros: "))

pesoI= peso / (altura ** 2)

if pesoI >= 18.5 and pesoI <=25:

    print ("você está no 'peso ideal' ")
else:
  print ("você não está no 'peso ideal' ")