# -*- coding: utf-8 -*-
"""lista estudo incompleta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MRAyc-tEzXCn2WWlx4flJslkTh8CB8a2
"""

series = []

while True:
  print("MENU\n")
  print("1. Adicionar série")
  print("2. Colocar em ordem alfabética")
  print("3. Enumerar séries")
  print("4. Sair")

  opcao= int(input("Digite a opção desejada: "))

  if opcao == 1:
    serie= input("Digite o nome da série: ")
    series.append(serie)
    print("Série adicionada com sucesso!\n")

  elif opcao == 2:
    ordemA= sorted(series)
    for serie in ordemA:
      print(serie)

  elif opcao == 3:
    print("\n")
    for x, serie in enumerate(series, start=1):
      print(f"{x}. {serie}")