# -*- coding: utf-8 -*-
"""pedra papel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHbZPPT6_rGgJ_rqnw9U8Rtza6vW3urC
"""



import random
bot = random.randint(1,3)

print ("PEDRA, PAPEL, TESOURA\n")
print ("---------------------\n")
jogada= str(input("digite sua jogada: "))

if jogada == "pedra" and bot == 1:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: pedra,\n")
  print ("VITÓRIA: empate")
if jogada == "pedra" and bot == 2:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: papel\n")
  print ("VITÓRIA: bot ganhou")
if jogada == "pedra" and bot == 3:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: tesoura\n")
  print ("VITÓRIA: você ganhou")
if jogada == "papel" and bot == 1:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: pedra\n")
  print ("VITÓRIA: você ganhou")
if jogada == "papel" and bot == 2:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: papel\n")
  print ("VITÓRIA: empate")
if jogada == "papel" and bot == 3:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: tesoura\n")
  print ("VITÓRIA: bot ganhou")
if jogada == "tesoura" and bot == 1:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: pedra\n")
  print ("VITÓRIA: bot ganhou")
if jogada == "tesoura" and bot == 2:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: papel\n")
  print ("VITÓRIA: você ganhou")
if jogada == "tesoura" and bot == 3:
  print ("SUA JOGADA: ",jogada,"\n")
  print ("BOT: tesoura\n")
  print ("VITÓRIA: empate")