# -*- coding: utf-8 -*-
"""treco dificil se

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TobN2X0mHIE7xGQ3vo7E7ne2Nfoy2miK
"""

sal= float(input ("digite o salário do funcionário: "))
gen= str(input ("digite o gênero do funcionário: "))
anosEmp= int(input ("digite quantos anos o funcionário está na empresa?: "))

if (gen == "feminino") and (anosEmp < 15):
  salN= sal + (sal * 5 / 100)
elif (gen == "feminino") and ((anosEmp >= 15) and (anosEmp <= 20)):
  salN= sal + (sal * 12 / 100)
elif (gen == "feminino") and (anosEmp > 20):
  salN= sal + (sal * 23 / 100)
elif (gen == "masculino") and (anosEmp < 20):
  salN= sal + (sal * 3 / 100)
elif (gen == "masculino") and ((anosEmp >= 20) and2 (anosEmp < 30)):
   salN= sal + (sal * 13 / 100)
else:
  salN= sal + (sal * 25 / 100)

print ("o novo salário será de R$",salN)